### ISSUE TITLE
Add instructions to remove reference to bspm

### ISSUE THREAD

**Issue by roberthadow** [cran4linux/bspm#80] opened 2023-11-07 13:34 UTC
I have inadvertently added bspm to some (unknown to me) startup script. At every restart of R (4.3.1) within RStudio (23.09.1 494)  under Ubuntu 22.04.3, I get the following error:

Error in loadNamespace(x) : there is no package called ‘bspm’

**The simplest solution is just to get rid of the call to bspm at startup.**  I don't compile packages. This minor issue seems to cause me other problems.  What file(s) should I look to edit?

I'd happily install the latest bspm, but when I try, I get the following:

> install.packages("bspm")
Installing package into ‘/home/rhadow/R/x86_64-pc-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/bspm_0.5.5.tar.gz'
Content type 'application/x-gzip' length 26800 bytes (26 KB)
==================================================
downloaded 26 KB

Error in loadNamespace(x) : there is no package called ‘bspm’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Warning in install.packages :
  installation of package ‘bspm’ had non-zero exit status

**Comment by eddelbuettel** [comment] 2023-11-07 13:48
You must been running a setup script, without telling us that, which _by design and documentation_ modified `/etc/R/Rprofile.site`.  If you want to undo that, edit the file.

**Comment by Enchufa2** [comment] 2023-11-07 15:03
Yes, note also that bspm cannot be the culprit here because 1) installing bspm per se does not modify your startup at all, and 2) you don't even have bspm installed, as the error you get states.

@eddelbuettel already pointed you in the right direction, so closing here.

**Closed by Enchufa2** 2023-11-07 15:03 UTC

**Comment by roberthadow** [comment] 2023-11-07 15:08
Thank you both.  Robert
